version: "3.8"

services:
  next-app:
    build: .
    container_name: blog-next
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://admin:123456@mongo-db:27017
      - NEXT_MONGO_DB_URI=mongodb://admin:123456@blog-mongo-db:27017
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:7
    container_name: blog-mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

